### PR TITLE
Updating to v3.0RC02

### PR DESCRIPTION
**Pull request by mjacoby**
This PR collects changes, issues and ToDos related to updating to v3.0RC02.

- **Enum Naming**
   Enum names for serialization are currently being generated rule-based. If possible, shall become constant, i.e. being provided as part of the input to the model generator and stored in the generated Enum classes. 
   Until this is available, generated names will be used.
- **Update handling of embeddedDataSpecifications** (see #14)
  Currently we expect the following format
  ```
       "embeddedDataSpecifications": [
           "embeddedDataSpecifications": {...},	// reference indicating the type
           "dataSpecificationContent": {...}		// actual data specification
       ]
  ```
  In the future, either embeddedDataSpecifications or dataSpecificationContent should be present.
  However, it is still undefined how the actual (sub-)type of dataSpecificationContent should be serialized, so this cannot be implemented right now.
  Therefore, this functionality is currently disabled until standardization progresses.
- ...

### CODE REVIEW

**Comment by sebbader** [comment]
Regarding

>* Update handling of embeddedDataSpecifications 

Things have changed in the meantime: Our previous approach ("dataSpecificationContent" and "dataSpecification" on the same level) has again got the 'ground truth' in the aas-specs community. With some minor deviations, though.

**Comment by mjacoby** [comment]
I noticed that with commit https://github.com/eclipse-digitaltwin/aas4j/pull/18/commits/2b0db63b5ead488ef5c17f19658387a77ed1d779 that naming scheme for singular builder methods changed.

Example [AssetInformationBuilder](https://github.com/eclipse-digitaltwin/aas4j/blob/2b0db63b5ead488ef5c17f19658387a77ed1d779/model/src/main/java/org/eclipse/aas4j/v3/model/builder/AssetInformationBuilder.java)
Previously we had the following two methods
`specificAssetIds(List<SpecificAssetId> specificAssetIds)`
`specificAssetId(SpecificAssetId specificAssetId)` 


now we have
`specificAssetIds(List<SpecificAssetId> specificAssetIds)`
`specificAssetIds(SpecificAssetId specificAssetIds)` 


The singular method previously had a singular method and paramter name but now has the plural name. 
@sebbader-sap Is this on purpose? If so, what are the intentions? Did we discuss/agree on this?

**Comment by sebbader-sap** [comment]
No, that was not on purpose (at least I don't remember it anymore) but more likely a mistake in the merging of the different generator branches. I will roll it back in the next model generation run.

**Comment by sebbader-sap** [comment]
I faced a few challenges with the proposed changes in the model. Listing them here to also ask for support:

> 1. Singular/plural method names in builder classes

The AAS attributes have been written in singular before, now the ones pointing to a list are written in plural in the sources. A `makePlural( singularAttributeName )` exists in the generator - but now we need a `makeSingular( pluralAttributeName )`. Any help is appreciated.

> 2. There are still wildcard imports in ...Builder and Default... classes

I think it's solvable but with a significant time invest. At the moment, I can't commit myself to get it fixed.

> 3. Enum modelling inconsistent/unclear

The enum "inheritance" problem is on the meta model/ontology level. v3.0 will change the enum structure anyway, so we should wait for the new ontology file.

4. and 5. are on my list.

**Comment by mjacoby** [comment]
1. Inversing the `makePlural` algorithm (https://github.com/eclipse-aas4j/aas4j-model-generator/blob/main/aas/src/templates/to_plural_form.rq) seems to be straight forward if I'm not missing something. Only problem might occur if have have words that end in 's' in singular because then we can't know if the 's' at the end is a plural 's' or part of the word itself.
If we do have such words, we have a problem and would require some additional mapping file for mapping between singular and plural...

3. Not a blocker from my perspective. We can fix this in the final release.

4. Regarding enums - right now we have an inconsistency as one enum element exists twice in our model and those instances are not the same or equals - this might cause problems in de-/serializing. But I'm fine with keeping it as-is until a concrete problem with it arises.

**Comment by mjacoby** [comment]
I just updated `dataformat-core` and `dataformat-json` and this seems fine and working now.
However, I removed the support for custom `DataSpecificationContent` implementation as it is unclear is they are allowed and how they should be handled with latest changes regarding serialization of `embeddedDataSpecification`. This causes `dataformat-xml` to break. However, `dataformat-xml` does not seem like it has been updated to `v3.0RC02` as there is e.g. no support for `SubmodelElementList`. Also the unit tests have been deactivated for `dataformat-xml` and when actived some of them failed. Not sure if we lost something while merging or it has never been implemented.
Additionally, some files are damaged due to incorrect merging, e.g. https://github.com/eclipse-aas4j/aas4j/blob/1a76a01d2f2b51bba2131b0ebb4a83e44a567616/dataformat-xml/src/test/resources/test_demo_full_example.xml#L725

I now consider `dataformat-core` and `dataformat-json` basically ready and would appreciate a review.

**Comment by FrankSchnicke** [comment]
After https://github.com/eclipse-aas4j/aas4j/pull/48 is merged we can also merge this PR.

**Comment by sebbader-sap** [comment]
I have just changed the state of this PR from `draft` to `ready for review`. I am personally not 'ready for review' (too many hours in front of the monitor) but will have a look again tomorrow. Would be great if you guys can also add your opinion here before we decide to merge it.

**Pull request merged**
