### PR TITLE
Tidies code in preparation for 1.0.0 release

### PR DESCRIPTION
**Pull request by FrankSchnicke**
This changeset includes the following changes:
- Removes RDF (closes https://github.com/eclipse-aas4j/aas4j/issues/108)
- Removes warnings by either changing the code to prevent them or use appropriate *@SuppressWarnings*
- Moves classes that are internally used but should not part of the public API to *\*.internal.\** packages
  - For the Serializer projects, the following classes are considered public: Serializer (including MixIns, CustomSerializers), Deserializer (including MixIns, CustomDeserializers) and Validation
  - Classes supporting AasUtils (e.g., Visitor, ...) are moved to internal
- Tidies AasUtils class
  - serializeEnumName/deserializeEnumName: Used by Enum(De)serializer, moved there  
  - Made private due to internal usage:
    - asString(Reference): Needed by resolve, will be made obsolete by adding *toString* method for Reference class
    - keyTypeToClass: Used by *resolve* & *sameAs*
    - clone: Used by *toReference*, however, it should be addressed by generic copy constructors for all classes
    - getAasProperties: Used by *resolve*
  - Removed due to unclear use case:  
    - parseReference
    - parseKey
    - getProperty
    - getCollectionContentType
    - getSubmodelTemplates
    - hasTemplate
    - isLocal (additionally, comment indicates that it may not be 100% accurate)

### CODE REVIEW

**Comment by FrankSchnicke** [comment]
@mjacoby @twebermartins @sebbader-sap @arnoweiss as discussed. What are your thoughts on the changes?

**Comment by mjacoby** [comment]
The PR looks good and can we accepted.


However, I am not sure if simply moving classes to an _*.internal.*_ package means they are no longer part of the API and can be safely changed without breaking any code using our library. One could argue, that everything that is accessible from outside code is part of our public API and therefore we should try to hide as much as possible by using the most strict access modifer possible. 

When doing so, we need to agree if we would like to have/expose any kind of utility functions, i.e. functions like `parseReference` (which has been removed) or `asString(Reference)` (which has been made private). I see that not having this makes developing and maintining the library easier but on the other hand having these utility functions might significantly improve user experience. My proposal would be to have some kind of utility functions but keep them minimal and down to really useful and often needed functionality.

**Comment by FrankSchnicke** [comment]
> However, I am not sure if simply moving classes to an __.internal.__ package means they are no longer part of the API and can be safely changed without breaking any code using our library. One could argue, that everything that is accessible from outside code is part of our public API and therefore we should try to hide as much as possible by using the most strict access modifer possible.

Moving classes to an internal package is proposed by https://jlbp.dev/JLBP-2. Of course, we can't prevent people from still using it. However, I would not consider classes in internal packages as part of the public API due to this best practice.

**Comment by arnoweiss** [comment]
The alternative would be to copy the classes to each dataformat-repo and set them private there, right?

**Comment by FrankSchnicke** [comment]
> The alternative would be to copy the classes to each dataformat-repo and set them private there, right?

This would only work for inner classes, thus would require lots of replication. In consequence, making them private by convention (i.e., moving them to an "internal" package) is in my opinion the only feasible way.

**Comment by arnoweiss** [comment]
I agree. There's two conflicting goals here: Avoid duplication and minimize API surface. Proposed solution is good compromise. Mergeable from my pov.

**Comment by mjacoby** [comment]
I agree, seems like the best solution at this time.

**Pull request merged**
