### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by FrankSchnicke**

### CODE REVIEW

**Comment by FrankSchnicke** [comment]
Closes #97

**Comment by arnoweiss** [comment]
Should we release this as a separate MS?

**Comment by FrankSchnicke** [comment]
It would make sense - however, I would like to double-check if there's any further update in preparation by @mjacoby to avoid too many releases in a short amount of time.

@mjacoby : Do you have anything in your pipeline we should wait for?

**Comment by HansG89** [comment]
> Closes #97

This will indeed solve the problem. However I saw the following warnings in my Quarkus application logs

```
2023-04-26 14:06:00,651 WARN  [org.ecl.dig.aas.v3.dat.cor.uti.ReflectionHelper] (Quarkus Main Thread) could not auto-resolve target class for mixin 'DataSpecificationPhysicalUnitMixin'

2023-04-26 14:06:00,652 WARN  [org.ecl.dig.aas.v3.dat.cor.uti.ReflectionHelper] (Quarkus Main Thread) could not auto-resolve target class for mixin 'LangStringMixin'
```

Should I ignore those warnings?

**Comment by FrankSchnicke** [comment]
Thanks for pointing this out, seems like this was missed during a refactoring. I will remove these Mixins.

**Comment by FrankSchnicke** [comment]
See https://github.com/eclipse-aas4j/aas4j/pull/99

**Comment by mjacoby** [comment]
There are currently no other updates from my side to include in a release.

However, we should think about versioning. Do we want to release each small change as seperate milestone? Is there any better way to do this, e.g. add some patch suffix or just release snapshot versions? 
As a user of aas4j I would assume that each milestone release provides some additional features.

**Comment by FrankSchnicke** [comment]
This change was also proposed by Dependabot, I merged it there (cf. https://github.com/eclipse-aas4j/aas4j/pull/100).

From the discussion, I think the best way forward would be to release this as a new milestone and have a discussion in two weeks on how to handle this better. Would this be fine with you?

**Comment by mjacoby** [comment]
Thb, I don't see the urgency in this PR that justifies "breaking" the naming scheme. However, if you consider it this urgent, I would be fine with using an arbitrary suffix to the version for now, e.g. `1.0.0-milestone-03.1` and discuss in the next meeting if we keep this naming scheme in the future.

**Comment by twebermartins** [comment]
Issue solved by #100. 

Release will be under '1.0.0-milestone-03.1'

**Pull request closed without merging**
