### PR TITLE
Fix de-/serialization for AAS with extension(s)

### PR DESCRIPTION
**Pull request by mjacoby**
This fixes the issue for JSON.
Additional unit tests should be added for XML and AASX.

Superseeds https://github.com/eclipse-aas4j/aas4j/pull/135

### CODE REVIEW

**Comment by alexgordtop** [comment]
Thanks, that fixes my issue :)

**Comment by mjacoby** [comment]
- [ ] Update full exampe to contain Extensions @mjacoby 
- [ ] Update XML & AASX serializer if required @FrankSchnicke

**Comment by mjacoby** [comment]
@FrankSchnicke Java classes are now available in `dataformat-core` (see https://github.com/eclipse-aas4j/aas4j/blob/bugfix/has-extensions/dataformat-core/src/test/java/org/eclipse/digitaltwin/aas4j/v3/dataformat/core/Examples.java). Please add corresponding unit tests for de-/serialization of XML.

**Comment by FrankSchnicke** [comment]
@mjacoby ready for review

**Pull request merged**
