### PR TITLE
Fixes XML-Serialization #60

### PR DESCRIPTION
**Pull request by arnoweiss**
There were a couple of bugs relating to the serialization of new meta-model-elements of RC02. 

https://github.com/eclipse-aas4j/aas4j/issues/60

### CODE REVIEW

**Comment by FrankSchnicke** [comment]
Hi Arno, 

would it be possible to update your Eclipse Account to use the same mail as this commit? 

Best regards,
Frank

**Comment by arnoweiss** [comment]
Still got some fixing to do anyway, no idea why my build didn't fail locally.

**Comment by FrankSchnicke** [comment]
There is right now an issue with the CI, see https://github.com/eclipse-aas4j/aas4j/pull/57. I'm still in the process of figuring out why the current state is failing with GitHub Actions. The Eclipse Jenkins instance is running the tests fine.

**Comment by twebermartins** [comment]
Just re-validated the ECA check. As @arnoweiss has a ECA signed, it is all ok now and ready for review

**Pull request merged**
